### ISSUE TITLE
Unix domain socket support

### ISSUE THREAD

**Issue by Kobaxidze256** [demostanis/gimmeasearx#15]
Go standard function net.Listen supports unix domain sockets. Shouldn't be too hard, right? I'm not comfortable with using port 8080 or picking another port.
Can systemd unit file be updated as well.

**Comment by Kobaxidze256** [comment]
yeah, it's easier to pick a file than a port.

**Comment by demostanis** [comment]
The website can't be just a file, it's not static.

**Comment by Kobaxidze256** [comment]
Sure, but I want to be able to connect to it over a unix domain socket. I can just give a user read/write permissions to it or make a root service filter requests to it, instead of having a random port open that anything can connect to.

**Comment by demostanis** [comment]
Ah, I get it. I didn't even know HTTP over Unix domain sockets was a thing. I tried to make the code support it, and I was able to connect to gimmeasearx through curl using `--unix-socket` option.
However, I can't access the socket with neither Firefox nor Chromium:
![image](https://user-images.githubusercontent.com/40673815/181750901-f18fb1b1-3d6c-4399-8c66-6b3d91e0d7a8.png)
That seems like a very weird issue, why don't you just use a firewall? Gimmeasearx binds to 127.0.0.1 by default anyway, not even 0.0.0.0.

**Comment by Kobaxidze256** [comment]
I was thinking about hosting it on my vps on a subdomain through nginx and possibly protecting it with a password similar to other services i have running.

**Comment by demostanis** [comment]
Isn't that doable with TCP..?

**Comment by Kobaxidze256** [comment]
Probably, but I'd prefer a unix socket.

**Comment by demostanis** [comment]
Feel free to fork the code and make the adequate changes.
