### ISSUE TITLE
site does not work anymore

### ISSUE THREAD

**Issue by maninthemiddle01** [demostanis/gimmeasearx#16]
onion site is not found by Tor-Browser

**Comment by demostanis** [comment]
i upgraded my server recently and didn't check the service's status. it should be back up.

**Comment by maninthemiddle01** [comment]
Did you update again? :)
Server is down again

**Comment by demostanis** [comment]
yes, sorry, i had a lot of issues with my server, it should be up again now

**Comment by maninthemiddle01** [comment]
No problem, thank you for your effort :)
