### ISSUE TITLE
Instance does not change when the search is repeated

### ISSUE THREAD

**Issue by fabianski7** [demostanis/gimmeasearx#5]
When searching for a term more than once (through the address bar), the instance selected for this search will always be the same.

Example:
When searching for wikipedia, I was redirected to the searx.fmac.xyz instance. And when redoing the search, it continued the same. 
This always happens, no matter how many times it is repeated. Only after closing the browser is possible.

If you search for something else, a new instance is chosen, but it will suffer the same problem if the search is redone.

**Comment by MrGeorgen** [comment]
because http server return "permanently moved" and not "temporarily moved"
https://github.com/demostanis/gimmeasearx/blob/a3ed27b1920c402f08d7a7aa495f1a897ae84717/cmd/main.go#L89

**Comment by fabianski7** [comment]
Thanks @MrGeorgen and @demostanis!
