### ISSUE TITLE
Support for instances not listed in searx.space

### ISSUE THREAD

**Issue by ElishaDaugherty** [demostanis/gimmeasearx#9]
There are several instances of searx that are not listed in the official repository. Some maintainers prefer not to include them for various reasons, like this https://github.com/searx/searx-instances/issues/15

I think this request might be a bit like the other issue https://github.com/demostanis/gimmeasearx/issues/6, when it was suggested the option to list the instances to be used by gimmeasearx. If you consider a duplicate, I can close this one and follow it through the other report.

> - List of allowed instances

Thanks!

**Comment by demostanis** [comment]
As gimmeasearx depends heavily on information provided by https://github.com/searx/searx-instances, such as HTML grade and comments, there would need to be a way to either have gimmeasearx extracting it itself, or have the user to provide it.
That would require major changes in the source code, but would still be possible.
Tell me which way sounds the best, and I (or you) might be able to implement it in the following days.

**Comment by ElishaDaugherty** [comment]
Since this is a more specific case, and users will probably add few instances, I see no problem in adding this manually.

**Comment by demostanis** [comment]
How should it be added to the UI? Should there just have a text input and a button to add one instance which will be fully trusted (I don't see any reason the user wouldn't add a trustnessless instance), or a full form to indicate all required values?
Are you up to send a pull request?

**Comment by ElishaDaugherty** [comment]
> Are you up to send a pull request?

I currently know nothing about GO. I just started learning python in this pandemic. I can help, but only in a few months 🤣

> How should it be added to the UI?

Well, I guess information like searx version, HTML grid and other things are not necessary. Since the user is adding an instance on his own, he probably should trust the maintainer or it's yours.

Then it would only be necessary to enter the URL and it would be "mixed" with all the others.

Does this make sense to you?

**Comment by demostanis** [comment]
Check master.
